### ISSUE TITLE
Add support for skipping based on directories

### ISSUE THREAD

**Issue by mx-psi** [jcchavezs/porto#13]
The current `--skip-files` option can only skip files based on the base file name. This is useful to e.g. skip by extension, but It doesn't help when you want to skip all files in a directory. For example, in opentelemetry-go we may want to skip this [`third_party` folder](https://github.com/open-telemetry/opentelemetry-go/tree/v1.0.1/exporters/jaeger/internal/third_party).

One alternative to be able to do this would be to change the `--skip-files` flag to skip based on the full filepath instead of the base filename; another would be to add  an analogous `--skip-dirs` to skip certain directories.

**Comment by jcchavezs** [comment]
This is a good feature @mx-psi. When it comes to API I am trying to follow gofmt, goimports and golangci-lint. In this case `skip-files` was a borrowed API from golangci-lint and I think it makes sense to also borrow `skip-dirs` (see https://golangci-lint.run/usage/configuration/).

Do you mind opening a PR with such change?

**Comment by mx-psi** [comment]
Sure, I will open one next week! Looking at the golangci-lint code, we may want to add ` --skip-dirs-use-default` too

**Comment by jcchavezs** [comment]
Sounds great!
